---
- name: ping
  hosts: 192.168.192.5
  become: yes

  tasks:
  - name: Descargar zip a /opt en cada computador
    get_url:
      url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.1.2.12/android-studio-2024.1.2.12-linux.tar.gz
      dest: /home/lis/awx-test
